services:
  homeserver:
    ### If you already built the Conduit image with 'docker build' or want to use a registry image,
    ### then you are ready to go.
    image:
      girlbossceo/conduwuit:latest
      ### If you want to build a fresh image from the sources, then comment the image line and uncomment the
      ### build lines. If you want meaningful labels in your built Conduit image, you should run docker compose like this:
      ### CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ') VERSION=$(grep -m1 -o '[0-9].[0-9].[0-9]' Cargo.toml) docker compose up -d
      # build:
      #     context: .
      #     args:
      #         CREATED: '2021-03-16T08:18:27Z'
      #         VERSION: '0.1.0'
      #         LOCAL: 'false'
      #         GIT_REF: origin/master
    restart: unless-stopped
    #ports:
    #  - 8448:6167
    volumes:
      - db:/var/lib/matrix-conduit/
    environment:
      CONDUWUIT_SERVER_NAME: example.com # EDIT THIS
      CONDUWUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUWUIT_DATABASE_BACKEND: rocksdb
      CONDUWUIT_PORT: 6167
      CONDUWUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUWUIT_ALLOW_REGISTRATION: 'true'
      CONDUWUIT_REGISTRATION_TOKEN: '1234567890' # EDIT THIS
      CONDUWUIT_ALLOW_FEDERATION: 'true'
      CONDUWUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUWUIT_TRUSTED_SERVERS:
        '["matrix.org"]'
        #CONDUWUIT_MAX_CONCURRENT_REQUESTS: 100
      CONDUWUIT_ADDRESS: 0.0.0.0
      CONDUWUIT_CONFIG: '' # Ignore this
    networks:
      - internal

  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8448:8448
    environment:
      CERTBOT_EMAIL: example@example.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    networks:
      - internal

networks:
  internal:
    attachable: true

volumes:
  db:
  letsencrypt:
